version: 2.1

commands:
  check-changed-files-or-halt:
    description: "Check changed files and half if target files are not changed"
    parameters:
      pattern:
        type: string
    steps:
      - checkout
      - run: git show -m HEAD --name-only --pretty="" | egrep -q '<< parameters.pattern >>' || circleci-agent step halt

  build-and-push:
    description: "Generate Dockerfile, then build and push the image"
    parameters:
      args:
        type: string
    steps:
      - run: |
          ./generate-Dockerfile.sh << parameters.args >>
          export CI_DOCKER_TAG=$(./generate-Dockerfile.sh --generate-tag << parameters.args >>)
          export CI_DOCKER_TAG=${CI_DOCKER_TAG}-${CIRCLE_SHA1:0:8}
          docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
          docker build --build-arg PYTHON_VERSION=3.7 -t ${DOCKER_REGISTRY}/primehub-notebook:${CI_DOCKER_TAG} .build
          docker push ${DOCKER_REGISTRY}/primehub-notebook:${CI_DOCKER_TAG}
  

jobs:
  build-base-notebook-cpu:
    machine:
      docker_layer_caching: true
    steps:
      - check-changed-files-or-halt:
          pattern: generate-Dockerfiles.sh|src/Dockerfile.(primehub|opencv)
      - build-and-push:
          args: "--base-notebook"

  build-tensorflow-notebook-cpu:
    machine:
      docker_layer_caching: true
    steps:
      - check-changed-files-or-halt:
          pattern: generate-Dockerfiles.sh|src/Dockerfile.(primehub|opencv|tensorflow|tensorboard)
      - build-and-push:
          args: "--tensorflow-notebook"

  build-pytorch-notebook-cpu:
    machine:
      docker_layer_caching: true
    steps:
      - check-changed-files-or-halt:
          pattern: generate-Dockerfiles.sh|src/Dockerfile.(primehub|opencv|pytorch)
      - build-and-push:
          args: "--pytorch-notebook"

  build-tensorflow-notebook-gpu:
    machine:
      docker_layer_caching: true
    steps:
      - check-changed-files-or-halt:
          pattern: generate-Dockerfiles.sh|src/Dockerfile.(primehub|opencv|tensorflow|tensorboard)
      - build-and-push:
          args: "--tensorflow-notebook --gpu"

  build-pytorch-notebook-gpu:
    machine:
      docker_layer_caching: true
    steps:
      - check-changed-files-or-halt:
          pattern: generate-Dockerfiles.sh|src/Dockerfile.(primehub|opencv|pytorch)
      - build-and-push:
          args: "--pytorch-notebook --gpu"


workflows:
  build-cpu-notebooks:
    jobs:
      - build-base-notebook-cpu
      - build-tensorflow-notebook-cpu
      - build-pytorch-notebook-cpu

  build-gpu-notebooks:
    jobs:
      - build-tensorflow-notebook-gpu
      - build-pytorch-notebook-gpu
