version: 2.1

jobs:
  build-base-notebook-cpu:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: |
          ./generate-Dockerfile.sh --base-notebook
          export CI_DOCKER_TAG=${./generate-Dockerfile.sh --generate-tag --base-notebook}
          export CI_DOCKER_TAG=${CI_DOCKER_TAG}-${CIRCLE_SHA1:0:8}
          docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
          docker build --build-arg PYTHON_VERSION=3.7 -t ${DOCKER_REGISTRY}/primehub-notebook:${CI_DOCKER_TAG} .build
          docker push ${DOCKER_REGISTRY}/primehub-notebook:${CI_DOCKER_TAG}

  build-tensorflow-notebook-cpu:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: |
          ./generate-Dockerfile.sh --tensorflow-notebook
          export CI_DOCKER_TAG=${./generate-Dockerfile.sh --generate-tag --tensorflow-notebook}
          export CI_DOCKER_TAG=${CI_DOCKER_TAG}-${CIRCLE_SHA1:0:8}
          docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
          docker build --build-arg PYTHON_VERSION=3.7 -t ${DOCKER_REGISTRY}/primehub-notebook:${CI_DOCKER_TAG} .build
          docker push ${DOCKER_REGISTRY}/primehub-notebook:${CI_DOCKER_TAG}

  build-pytorch-notebook-cpu:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: |
          ./generate-Dockerfile.sh --pytorch-notebook
          export CI_DOCKER_TAG=${./generate-Dockerfile.sh --generate-tag --pytorch-notebook}
          export CI_DOCKER_TAG=${CI_DOCKER_TAG}-${CIRCLE_SHA1:0:8}
          docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
          docker build --build-arg PYTHON_VERSION=3.7 -t ${DOCKER_REGISTRY}/primehub-notebook:${CI_DOCKER_TAG} .build
          docker push ${DOCKER_REGISTRY}/primehub-notebook:${CI_DOCKER_TAG}

  build-tensorflow-notebook-gpu:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: |
          ./generate-Dockerfile.sh --tensorflow-notebook --gpu
          export CI_DOCKER_TAG=${./generate-Dockerfile.sh --generate-tag --tensorflow-notebook --gpu}
          export CI_DOCKER_TAG=${CI_DOCKER_TAG}-${CIRCLE_SHA1:0:8}
          docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
          docker build --build-arg PYTHON_VERSION=3.7 -t ${DOCKER_REGISTRY}/primehub-notebook:${CI_DOCKER_TAG} .build
          docker push ${DOCKER_REGISTRY}/primehub-notebook:${CI_DOCKER_TAG}

  build-pytorch-notebook-gpu:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: |
          ./generate-Dockerfile.sh --pytorch-notebook --gpu
          export CI_DOCKER_TAG=${./generate-Dockerfile.sh --generate-tag --pytorch-notebook --gpu}
          export CI_DOCKER_TAG=${CI_DOCKER_TAG}-${CIRCLE_SHA1:0:8}
          docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
          docker build --build-arg PYTHON_VERSION=3.7 -t ${DOCKER_REGISTRY}/primehub-notebook:${CI_DOCKER_TAG} .build
          docker push ${DOCKER_REGISTRY}/primehub-notebook:${CI_DOCKER_TAG}

workflows:
  build-cpu-notebooks:
    jobs:
      - build-base-notebook-cpu
      - build-tensorflow-notebook-cpu
      - build-pytorch-notebook-cpu

  build-gpu-notebooks:
    jobs:
      - build-tensorflow-notebook-gpu
      - build-pytorch-notebook-gpu
